CREATE SEQUENCE ASKREPLY_SEQ;

CREATE TABLE TBL_ASKREPLY(
 ASKREPLY_NUM NUMBER(10),
 ASKBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(100),
 REPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT ASKREPLY_PK PRIMARY KEY(ASKREPLY_NUM),
 CONSTRAINT ASKREPLY_ASKBOARD_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM),
 CONSTRAINT ASKREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );
 
SELECT *FROM TBL_ASKREPLY;

DROP TABLE TBL_ASKREPLY;

CREATE TABLE TBL_ASKREPLY(
 ASKREPLY_NUM NUMBER(10),
 ASKBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(200),
 REPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT ASKREPLY_PK PRIMARY KEY(ASKREPLY_NUM),
 CONSTRAINT ASKREPLY_ASKBOARD_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM),
 CONSTRAINT ASKREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );

SELECT * FROM TBL_ASKREPLY;

DROP TABLE TBL_ASKREPLY;

CREATE TABLE TBL_ASKREPLY(
 ASKREPLY_NUM NUMBER(10),
 ASKBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(200),
 ASKREPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT ASKREPLY_PK PRIMARY KEY(ASKREPLY_NUM),
 CONSTRAINT ASKREPLY_ASKBOARD_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM),
 CONSTRAINT ASKREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );

SELECT * FROM TBL_ASKREPLY;

SELECT * FROM TBL_ASKBOARD;

INSERT INTO TBL_ASKREPLY (ASKREPLY_NUM, ASKBOARD_NUM, USER_ID, ASKREPLY_CONTENT)
VALUES (ASKREPLY_SEQ.NEXTVAL, 2, 'sanga0830', '댓글 테스트4');

SELECT * FROM TBL_ASKREPLY;

