CREATE TABLE TBL_GAL(
	GAL_NUM NUMBER(30),
	GAL_ID VARCHAR2(100),
	GAL_BUILDINGTYPE VARCHAR2(100),
	GAL_ROOMTYPE VARCHAR2(100),
	GAL_COLORTYPE VARCHAR2(100),
	GAL_FILEPATH VARCHAR2(100),
	GAL_DATE DATE,
	CONSTRAINT GAL_PK PRIMARY KEY(GAL_NUM),
	CONSTRAINT GAL_FK FOREIGN KEY(GAL_ID) REFERENCES TBL_USER(USER_ID)
);

SELECT * FROM TBL_GAL;

CREATE SEQUENCE GAL_SEQ;
TRUNCATE TABLE TBL_GAL_FILES ;
ALTER TABLE TBL_GAL DROP COLUMN GAL_LIKE;
ALTER TABLE TBL_GAL ADD COLUMN GAL_FILE_PATH VARCHAR2(300);

DELETE FROM TBL_GAL WHERE GAL_NUM = 11;

CREATE TABLE TBL_GAL_FILES(
	GAL_FILE_NAME VARCHAR2(100),
	GAL_NUM NUMBER(10),
	CONSTRAINT GAL_FILE_PK PRIMARY KEY(GAL_FILE_NAME),
	CONSTRAINT GAL_FILE_FK FOREIGN KEY(GAL_NUM) REFERENCES TBL_GAL(GAL_NUM)
);

SELECT * FROM TBL_GAL_FILES;
TRUNCATE TABLE TBL_COMMUNITY;

TRUNCATE TABLE TBL_COMMUNITY_FILES ;
DROP TABLE TBL_GAL;
DROP TABLE TBL_GAL_FILES;

CREATE TABLE TBL_COMMUNITY(
	COMMUNITY_NUM NUMBER(30),
	COMMUNITY_TITLE VARCHAR2(1000),
	COMMUNITY_ID	VARCHAR2(100),
	COMMUNITY_CONTENT VARCHAR2(3000),
	READCOUNT	NUMBER(10),
	COMMUNITY_DATE DATE,
	CONSTRAINT COMMUNITY_PK PRIMARY KEY(COMMUNITY_NUM),
	CONSTRAINT COMMUNITY_FK FOREIGN KEY(COMMUNITY_ID) REFERENCES TBL_USER(USER_ID)
);

CREATE TABLE TBL_COMMUNITY_FILES(
	COMMUNITY_FILE_NAME VARCHAR2(100),
	COMMUNITY_NUM NUMBER(10),
	CONSTRAINT COMMUNITY_FILE_PK PRIMARY KEY(COMMUNITY_FILE_NAME),
	CONSTRAINT COMMUNITY_FILE_FK FOREIGN KEY(COMMUNITY_NUM) REFERENCES TBL_COMMUNITY(COMMUNITY_NUM)
);
DROP TABLE TBL_COMMUNITY ;
DROP TABLE TBL_COMMUNITY_FILES;
CREATE SEQUENCE COMMUNITY_SEQ;
SELECT * FROM TBL_COMMUNITY_FILES WHERE COMMUNITY_NUM = 9;
SELECT * FROM (SELECT ROWNUM, D.* FROM (SELECT * FROM TBL_COMMUNITY ORDER BY COMMUNITY_NUM DESC) D) B  WHERE B.R BETWEEN 1 AND 10;

SELECT * FROM   (SELECT ROWNUM R, D.* FROM    (SELECT * FROM TBL_COMMUNITY ORDER BY COMMUNITY_NUM DESC) D) B  WHERE B.R BETWEEN 1 AND 10;