CREATE SEQUENCE HELPREPLY_SEQ;

CREATE TABLE TBL_HELPREPLY(
 HELPREPLY_NUM NUMBER(10),
 HELPBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(100),
 REPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT HELPREPLY_PK PRIMARY KEY(HELPREPLY_NUM),
 CONSTRAINT HELPREPLY_HELPBOARD_FK FOREIGN KEY(HELPBOARD_NUM) REFERENCES TBL_ASKHELP(ASKHELP_NUM),
 CONSTRAINT HELPREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );
 
SELECT *FROM TBL_HELPREPLY;

SELECT * FROM TBL_ASKHELP;

INSERT INTO SCOTT.TBL_HELPREPLY 
(HELPREPLY_NUM, HELPBOARD_NUM, USER_ID, REPLY_CONTENT)
VALUES (HELPREPLY_SEQ.NEXTVAL, 60, 'asdf', 'hello');