CREATE SEQUENCE COMMUNITY_REPLY_SEQ;

CREATE TABLE TBL_COMMUNITY_REPLY(
	COMMUNITY_REPLY_NUM NUMBER(10),
	COMMUNITY_NUM NUMBER(10),
	USER_ID VARCHAR2(100),
	COMMUNITY_REPLY_CONTENT VARCHAR2(4000),
	CONSTRAINT COMMUNITY_REPLY_PK PRIMARY KEY(COMMUNITY_REPLY_NUM),
	CONSTRAINT REPLY_COMMUNITY_FK FOREIGN KEY(COMMUNITY_NUM) REFERENCES TBL_COMMUNITY(COMMUNITY_NUM),
	CONSTRAINT REPLY_USER_FK FOREIGN KEY (USER_ID) REFERENCES TBL_USER(USER_ID)
);

SELECT * FROM TBL_COMMUNITY_REPLY;

INSERT INTO SCOTT.TBL_COMMUNITY_REPLY
(COMMUNITY_REPLY_NUM, COMMUNITY_NUM, USER_ID, COMMUNITY_REPLY_CONTENT)
VALUES(COMMUNITY_REPLY_SEQ.NEXTVAL, 9, 'buj68425', '댓글 테스트 4');
