CREATE TABLE TBL_USER
(
    USER_NUM               NUMBER          NOT NULL, 
    USER_ID                VARCHAR2(200)    NULL, 
    USER_PW                VARCHAR2(200)    NULL, 
    USER_PHONE_NUMBER      VARCHAR2(200)    NULL, 
    USER_NAME              VARCHAR2(200)    NULL, 
    USER_EMAIL             VARCHAR2(200)    NULL, 
    USER_LIVINGROOM_C      VARCHAR2(200)    NULL, 
    USER_KITCHEN_C         VARCHAR2(200)    NULL, 
    USER_ROOM_C              VARCHAR2(200)    NULL, 
    USER_GENDER            VARCHAR2(200)    NULL, 
    USER_ZIPCODE			VARCHAR2(200)  NULL,
    USER_ADDRESS           VARCHAR2(200)    NULL, 
    USER_ADDRESS_DETAIL    VARCHAR2(200)    NULL, 
    USER_ADDRESS_ETC       VARCHAR2(200)    NULL, 
    ADMIN                  NUMBER           NULL, 
    USER_AGE NUMBER NULL,
    CONSTRAINT TBL_USER_PK PRIMARY KEY (USER_ID)
);

SELECT * FROM TBL_USER;

CREATE SEQUENCE SEQ_USERNUM;

DROP TABLE TBL_USER;

CREATE TABLE TBL_GAL(
	GAL_NUM NUMBER(30),
	GAL_ID VARCHAR2(100),
	GAL_BUILDINGTYPE VARCHAR2(100),
	GAL_ROOMTYPE VARCHAR2(100),
	GAL_COLORTYPE VARCHAR2(100),
	GAL_FILEPATH VARCHAR2(100),
	GAL_DATE DATE,
	CONSTRAINT GAL_PK PRIMARY KEY(GAL_NUM),
	CONSTRAINT GAL_FK FOREIGN KEY(GAL_ID) REFERENCES TBL_USER(USER_ID)
);

SELECT * FROM TBL_GAL;

CREATE SEQUENCE GAL_SEQ;
TRUNCATE TABLE TBL_GAL_FILES ;
ALTER TABLE TBL_GAL DROP COLUMN GAL_LIKE;
ALTER TABLE TBL_GAL ADD COLUMN GAL_FILE_PATH VARCHAR2(300);

DELETE FROM TBL_GAL_FILES WHERE GAL_NUM = 31;

CREATE TABLE TBL_GAL_FILES(
	GAL_FILE_NAME VARCHAR2(100),
	GAL_NUM NUMBER(10),
	CONSTRAINT GAL_FILE_PK PRIMARY KEY(GAL_FILE_NAME),
	CONSTRAINT GAL_FILE_FK FOREIGN KEY(GAL_NUM) REFERENCES TBL_GAL(GAL_NUM)
);

SELECT * FROM TBL_GAL_FILES;
TRUNCATE TABLE TBL_COMMUNITY;

TRUNCATE TABLE TBL_COMMUNITY_FILES ;
DROP TABLE TBL_GAL;
DROP TABLE TBL_GAL_FILES;

CREATE TABLE TBL_COMMUNITY(
	COMMUNITY_NUM NUMBER(30),
	COMMUNITY_TITLE VARCHAR2(1000),
	COMMUNITY_ID	VARCHAR2(100),
	COMMUNITY_CONTENT VARCHAR2(3000),
	READCOUNT	NUMBER(10),
	COMMUNITY_DATE DATE,
	CONSTRAINT COMMUNITY_PK PRIMARY KEY(COMMUNITY_NUM),
	CONSTRAINT COMMUNITY_FK FOREIGN KEY(COMMUNITY_ID) REFERENCES TBL_USER(USER_ID)
);

CREATE TABLE TBL_COMMUNITY_FILES(
	COMMUNITY_FILE_NAME VARCHAR2(100),
	COMMUNITY_NUM NUMBER(10),
	CONSTRAINT COMMUNITY_FILE_PK PRIMARY KEY(COMMUNITY_FILE_NAME),
	CONSTRAINT COMMUNITY_FILE_FK FOREIGN KEY(COMMUNITY_NUM) REFERENCES TBL_COMMUNITY(COMMUNITY_NUM)
);
DROP TABLE TBL_COMMUNITY ;
DROP TABLE TBL_COMMUNITY_FILES;
CREATE SEQUENCE COMMUNITY_SEQ;

CREATE TABLE TBL_ASKHELP(
	ASKHELP_NUM NUMBER(10),
	ASKHELP_TITLE VARCHAR2(1000),
	ASKHELP_CONTENT VARCHAR2(3000),
	ASKHELP_ID VARCHAR2(37),
	ASKHELP_DATE DATE,
	ASKHELP_READCOUNT NUMBER(37),
	CONSTRAINT ASKHELP_PK PRIMARY KEY(ASKHELP_NUM),
	CONSTRAINT ASKHELP_FK FOREIGN KEY(ASKHELP_ID) REFERENCES TBL_USER(USER_ID)
);

