CREATE SEQUENCE ASKHELP_SEQ;

CREATE TABLE TBL_ASKHELP(
	ASKHELP_NUM NUMBER(10),
	ASKHELP_TITLE VARCHAR2(1000),
	ASKHELP_CONTENT VARCHAR2(3000),
	ASKHELP_ID VARCHAR2(37),
	ASKHELP_DATE DATE,
	ASKHELP_READCOUNT NUMBER(37),
	CONSTRAINT ASKHELP_PK PRIMARY KEY(ASKHELP_NUM),
	CONSTRAINT ASKHELP_FK FOREIGN KEY(ASKHELP_ID) REFERENCES TBL_USER(USER_ID)
);


CREATE TABLE TBL_ASKREPLY(
 ASKREPLY_NUM NUMBER(10),
 ASKBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(200),
 ASKREPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT ASKREPLY_PK PRIMARY KEY(ASKREPLY_NUM),
 CONSTRAINT ASKREPLY_ASKBOARD_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM),
 CONSTRAINT ASKREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );
DROP TABLE TBL_ASKREPLY;

SELECT * FROM TBL_USER;

SELECT * FROM TBL_ASKHELP;
DROP TABLE TBL_ASKHELP;

ALTER TABLE TBL_ASKHELP DROP CONSTRAINT ASKHELP_FK;

ALTER TABLE TBL_ASKHELP DROP CONSTRAINT ASKHELP_PK CASCADE;
ALTER TABLE TBL_ASKHELP ADD CONSTRAINT ASKHELP_PK PRIMARY KEY(ASKHELP_NUM);

INSERT INTO TBL_ASKHELP
(ASKHELP_NUM, ASKHELP_TITLE, ASKHELP_CONTENT, ASKHELP_ID, ASKHELP_DATE, ASKHELP_READCOUNT)
VALUES (23, 'dfd', 'asdf', 'asdfg', SYSDATE, 1);

SELECT * FROM (SELECT ROWNUM R, T.* FROM (SELECT * FROM TBL_ASKHELP B ORDER BY 1 DESC) T) S
WHERE S.R > 10 AND S.R < 21

DROP TABLE TBL_EXPERT ;

CREATE SEQUENCE HELPREPLY_SEQ;
CREATE TABLE TBL_HELPREPLY(
 HELPREPLY_NUM NUMBER(10),
 HELPBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(100),
 REPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT HELPREPLY_PK PRIMARY KEY(HELPREPLY_NUM),
 CONSTRAINT HELPREPLY_HELPBOARD_FK FOREIGN KEY(HELPBOARD_NUM) REFERENCES TBL_ASKHELP(ASKHELP_NUM),
 CONSTRAINT HELPREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );
 
CREATE TABLE T_EXPERT
(
    EX_NUM         NUMBER           NOT NULL, 
    EX_ID          VARCHAR2(100)    NULL, 
    EX_PW          VARCHAR2(100)    NULL, 
    EX_NAME        VARCHAR2(100)    NULL, 
    EX_EXPERT_NAME    VARCHAR2(100)    NULL, 
    EX_PHONE_NUM 		VARCHAR(100) NULL,
    EX_EMAIL        VARCHAR2(100)    NULL, 
    EX_GENDER      VARCHAR2(100)    NULL,
    EX_ZIPCODE     VARCHAR2(100)	NULL,
    EX_ADDRESS	   VARCHAR2(100)	NULL,
    EX_ADDRESS_DETAIL VARCHAR2(100)	NULL,
    EX_ADDRESS_ETC	VARCHAR2(100)	NULL,
    CONSTRAINT T_EXPERT_PK PRIMARY KEY (EX_NUM)
);


CREATE SEQUENCE SEQ_E_NUMBER
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;

SELECT * FROM T_EXPERT;
SELECT * FROM T_FILES;


CREATE TABLE T_FILES(
	FILE_NAME_EX  VARCHAR2(100) NULL,
	EX_NUM         NUMBER	 NULL,
	 CONSTRAINT  T_FILES_PK PRIMARY KEY(FILE_NAME_EX),
	 CONSTRAINT  T_FILES_FK FOREIGN KEY(EX_NUM ) REFERENCES  T_EXPERT(EX_NUM )
);