SELECT * FROM TBL_BOARD;

DROP TABLE TBL_BOARD;

SELECT *FROM TBL_BOARD;

CREATE SEQUENCE ASKBOARD_SEQ;

CREATE TABLE TBL_ASKBOARD(
	ASKBOARD_NUM NUMBER(10),
	ASKBOARD_ID VARCHAR2(100),
	ASKBOARD_TITLE VARCHAR2(1000), 
	ASKBOARD_CONTENT VARCHAR2(3000), /*내용*/
	ASKBOARD_DATE DATE, 
	CONSTRAINT ASKBOARD_PK PRIMARY KEY(ASKBOARD_NUM)
	CONSTRAINT ASKBOARD_FK FOREIGN KEY(ASKBOARD_ID) REFERENCES TBL_USER(USER_ID)
);

ALTER TABLE TBL_USER DROP CONSTRAINT TBL_USER_PK CASCADE;
ALTER TABLE TBL_USER ADD CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID);

DROP TABLE TBL_ASKBOARD;

CREATE TABLE TBL_ASKBOARD (
	ASKBOARD_NUM NUMBER(10),
	ASKBOARD_ID VARCHAR2(100),
	ASKBOARD_TITLE VARCHAR2(1000), 
	ASKBOARD_CONTENT VARCHAR2(3000),
	ASKBOARD_DATE DATE, 
	CONSTRAINT ASKBOARD_PK PRIMARY KEY(ASKBOARD_NUM),
	CONSTRAINT ASKBOARD_FK FOREIGN KEY(ASKBOARD_ID) REFERENCES TBL_USER(USER_ID)
	);

SELECT *FROM TBL_ASKBOARD;

ALTER TABLE TBL_ASKBOARD ADD READCOUNT NUMBER(10) default 0;

SELECT * FROM TBL_ASKBOARD;

INSERT INTO SCOTT.TBL_ASKBOARD
(ASKBOARD_NUM, ASKBOARD_ID, ASKBOARD_TITLE, ASKBOARD_CONTENT, ASKBOARD_DATE, READCOUNT)
VALUES(0, '', '', '', '', 0);

INSERT INTO TBL_ASKBOARD 
VALUES (ASKBOARD_SEQ.NEXTVAL, 'sanga0830','문의합니다1', '인테리어문의합니다1', SYSDATE,0);

CREATE TABLE ASKFILES(
	ASKFILE_NAME VARCHAR2(100),
	ASKBOARD_NUM NUMBER(10),
	CONSTRAINT ASKFILES_PK PRIMARY KEY(ASKFILE_NAME),
	CONSTRAINT ASKFILES_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM) 
);

SELECT *FROM ASKFILES;

DROP TABLE ASKFILES;

CREATE TABLE TBL_ASKFILES(
	ASKFILE_NAME VARCHAR2(100),
	ASKBOARD_NUM NUMBER(10),
	CONSTRAINT ASKFILES_PK PRIMARY KEY(ASKFILE_NAME),
	CONSTRAINT ASKFILES_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM) 
);

SELECT * FROM TBL_ASKFILES;
CREATE TABLE TBL_ASKREPLY(
 ASKREPLY_NUM NUMBER(10),
 ASKBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(200),
 ASKREPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT ASKREPLY_PK PRIMARY KEY(ASKREPLY_NUM),
 CONSTRAINT ASKREPLY_ASKBOARD_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM),
 CONSTRAINT ASKREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );
