//회원
CREATE TABLE TBL_USER
(
    USER_NUM               NUMBER          NOT NULL, 
    USER_ID                VARCHAR2(200)    NULL, 
    USER_PW                VARCHAR2(200)    NULL, 
    USER_PHONE_NUMBER      VARCHAR2(200)    NULL, 
    USER_NAME              VARCHAR2(200)    NULL, 
    USER_EMAIL             VARCHAR2(200)    NULL, 
    USER_LIVINGROOM_C      VARCHAR2(200)    DEFAULT 'X', 
    USER_KITCHEN_C         VARCHAR2(200)    DEFAULT 'X', 
    USER_ROOM_C              VARCHAR2(200)  DEFAULT 'X',
    USER_AGE NUMBER NULL,
    USER_GENDER            VARCHAR2(200)    NULL, 
    USER_ZIPCODE			VARCHAR2(200)  NULL,
    USER_ADDRESS           VARCHAR2(200)    NULL, 
    USER_ADDRESS_DETAIL    VARCHAR2(200)    NULL, 
    USER_ADDRESS_ETC       VARCHAR2(200)    NULL, 
    ADMIN                  NUMBER           NULL, 
    CONSTRAINT TBL_USER_PK PRIMARY KEY (USER_ID)
);

CREATE SEQUENCE SEQ_USERNUM;

CREATE TABLE T_EXPERT
(
    EX_NUM         NUMBER           NOT NULL, 
    EX_ID          VARCHAR2(100)    NULL, 
    EX_PW          VARCHAR2(100)    NULL, 
    EX_NAME        VARCHAR2(100)    NULL, 
    EX_EXPERT_NAME    VARCHAR2(100)    NULL, 
    EX_PHONE_NUM 		VARCHAR(100) NULL,
    EX_EMAIL        VARCHAR2(100)    NULL, 
    EX_GENDER      VARCHAR2(100)    NULL,
    EX_ZIPCODE     VARCHAR2(100)	NULL,
    EX_ADDRESS	   VARCHAR2(100)	NULL,
    EX_ADDRESS_DETAIL VARCHAR2(100)	NULL,
    EX_ADDRESS_ETC	VARCHAR2(100)	NULL,
    CONSTRAINT T_EXPERT_PK PRIMARY KEY (EX_NUM)
);

CREATE SEQUENCE SEQ_E_NUMBER;

SELECT * FROM T_EXPERT;
SELECT * FROM T_FILES;


CREATE TABLE T_FILES(
	FILE_NAME_EX  VARCHAR2(100) NULL,
	EX_NUM         NUMBER	 NULL,
	 CONSTRAINT  T_FILES_PK PRIMARY KEY(FILE_NAME_EX),
	 CONSTRAINT  T_FILES_FK FOREIGN KEY(EX_NUM ) REFERENCES  T_EXPERT(EX_NUM )
);
/*커뮤니티*/
CREATE TABLE TBL_COMMUNITY(
	COMMUNITY_NUM NUMBER(30),
	COMMUNITY_TITLE VARCHAR2(1000),
	COMMUNITY_ID	VARCHAR2(100),
	COMMUNITY_CONTENT VARCHAR2(3000),
	READCOUNT	NUMBER(10),
	COMMUNITY_DATE DATE,
	CONSTRAINT COMMUNITY_PK PRIMARY KEY(COMMUNITY_NUM),
	CONSTRAINT COMMUNITY_FK FOREIGN KEY(COMMUNITY_ID) REFERENCES TBL_USER(USER_ID)
);

CREATE TABLE TBL_COMMUNITY_FILES(
	COMMUNITY_FILE_NAME VARCHAR2(100),
	COMMUNITY_NUM NUMBER(10),
	CONSTRAINT COMMUNITY_FILE_PK PRIMARY KEY(COMMUNITY_FILE_NAME),
	CONSTRAINT COMMUNITY_FILE_FK FOREIGN KEY(COMMUNITY_NUM) REFERENCES TBL_COMMUNITY(COMMUNITY_NUM)
);

CREATE SEQUENCE COMMUNITY_SEQ;
/*커뮤니티댓ㄱㄹ*/
CREATE SEQUENCE COMMUNITY_REPLY_SEQ;

CREATE TABLE TBL_COMMUNITY_REPLY(
	COMMUNITY_REPLY_NUM NUMBER(10),
	COMMUNITY_NUM NUMBER(10),
	USER_ID VARCHAR2(100),
	COMMUNITY_REPLY_CONTENT VARCHAR2(4000),
	CONSTRAINT COMMUNITY_REPLY_PK PRIMARY KEY(COMMUNITY_REPLY_NUM),
	CONSTRAINT REPLY_COMMUNITY_FK FOREIGN KEY(COMMUNITY_NUM) REFERENCES TBL_COMMUNITY(COMMUNITY_NUM),
	CONSTRAINT REPLY_USER_FK FOREIGN KEY (USER_ID) REFERENCES TBL_USER(USER_ID)
);
/*//갤러리*/
CREATE TABLE TBL_GAL(
	GAL_NUM NUMBER(30),
	GAL_ID VARCHAR2(100),
	GAL_BUILDINGTYPE VARCHAR2(100),
	GAL_ROOMTYPE VARCHAR2(100),
	GAL_COLORTYPE VARCHAR2(100),
	GAL_FILEPATH VARCHAR2(100),
	GAL_DATE DATE,
	CONSTRAINT GAL_PK PRIMARY KEY(GAL_NUM),
	CONSTRAINT GAL_FK FOREIGN KEY(GAL_ID) REFERENCES TBL_USER(USER_ID)
);
CREATE TABLE TBL_GAL_FILES(
	GAL_FILE_NAME VARCHAR2(100),
	GAL_NUM NUMBER(10),
	CONSTRAINT GAL_FILE_PK PRIMARY KEY(GAL_FILE_NAME),
	CONSTRAINT GAL_FILE_FK FOREIGN KEY(GAL_NUM) REFERENCES TBL_GAL(GAL_NUM)
);
CREATE SEQUENCE GAL_SEQ;
/*고객센터*/
CREATE SEQUENCE ASKHELP_SEQ;
CREATE TABLE TBL_ASKHELP(
	ASKHELP_NUM NUMBER(10),
	ASKHELP_TITLE VARCHAR2(1000),
	ASKHELP_CONTENT VARCHAR2(3000),
	ASKHELP_ID VARCHAR2(37),
	ASKHELP_DATE DATE,
	ASKHELP_READCOUNT NUMBER(37),
	CONSTRAINT ASKHELP_PK PRIMARY KEY(ASKHELP_NUM),
	CONSTRAINT ASKHELP_FK FOREIGN KEY(ASKHELP_ID) REFERENCES TBL_USER(USER_ID)
);
CREATE SEQUENCE HELPREPLY_SEQ;
CREATE TABLE TBL_HELPREPLY(
 HELPREPLY_NUM NUMBER(10),
 HELPBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(100),
 REPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT HELPREPLY_PK PRIMARY KEY(HELPREPLY_NUM),
 CONSTRAINT HELPREPLY_HELPBOARD_FK FOREIGN KEY(HELPBOARD_NUM) REFERENCES TBL_ASKHELP(ASKHELP_NUM),
 CONSTRAINT HELPREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );
 
/*//조언게시판*/
CREATE TABLE TBL_ASKBOARD (
	ASKBOARD_NUM NUMBER(10),
	ASKBOARD_ID VARCHAR2(100),
	ASKBOARD_TITLE VARCHAR2(1000), 
	ASKBOARD_CONTENT VARCHAR2(3000),
	ASKBOARD_DATE DATE, 
	CONSTRAINT ASKBOARD_PK PRIMARY KEY(ASKBOARD_NUM),
	CONSTRAINT ASKBOARD_FK FOREIGN KEY(ASKBOARD_ID) REFERENCES TBL_USER(USER_ID)
	);
	
CREATE TABLE TBL_ASKFILES(
	ASKFILE_NAME VARCHAR2(100),
	ASKBOARD_NUM NUMBER(10),
	CONSTRAINT ASKFILES_PK PRIMARY KEY(ASKFILE_NAME),
	CONSTRAINT ASKFILES_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM) 
);

CREATE TABLE TBL_ASKREPLY(
 ASKREPLY_NUM NUMBER(10),
 ASKBOARD_NUM NUMBER(10),
 USER_ID VARCHAR2(200),
 ASKREPLY_CONTENT VARCHAR2(4000),
 CONSTRAINT ASKREPLY_PK PRIMARY KEY(ASKREPLY_NUM),
 CONSTRAINT ASKREPLY_ASKBOARD_FK FOREIGN KEY(ASKBOARD_NUM) REFERENCES TBL_ASKBOARD(ASKBOARD_NUM),
 CONSTRAINT ASKREPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
 );
 CREATE SEQUENCE ASKREPLY_SEQ;
 CREATE SEQUENCE ASKBOARD_SEQ;