CREATE TABLE TBL_USER
(
    USER_NUM               NUMBER          NOT NULL, 
    USER_ID                VARCHAR2(200)    NULL, 
    USER_PW                VARCHAR2(200)    NULL, 
    USER_PHONE_NUMBER      VARCHAR2(200)    NULL, 
    USER_NAME              VARCHAR2(200)    NULL, 
    USER_EMAIL             VARCHAR2(200)    NULL, 
    USER_LIVINGROOM_C      VARCHAR2(200)    DEFAULT 'X', 
    USER_KITCHEN_C         VARCHAR2(200)    DEFAULT 'X', 
    USER_ROOM_C              VARCHAR2(200)  DEFAULT 'X',
    USER_AGE NUMBER NULL,
    USER_GENDER            VARCHAR2(200)    NULL, 
    USER_ZIPCODE			VARCHAR2(200)  NULL,
    USER_ADDRESS           VARCHAR2(200)    NULL, 
    USER_ADDRESS_DETAIL    VARCHAR2(200)    NULL, 
    USER_ADDRESS_ETC       VARCHAR2(200)    NULL, 
    ADMIN                  NUMBER           NULL, 
    CONSTRAINT TBL_USER_PK PRIMARY KEY (USER_ID)
);
SELECT * FROM TBL_USER ;

CREATE SEQUENCE SEQ_USERNUM;

DROP TABLE TBL_USER;